export const SAVE_COMMENT = "SAVE_COMMENT";
export const FETCH_COMMENT_START = "FETCH_COMMENT_START";
export const FETCH_COMMENT_SUCCESS = "FETCH_COMMENT_SUCCESS";
export const FETCH_COMMENT_FAIL = "FETCH_COMMENT_FAIL";
